create table status
(
    id   bigint generated by default as identity primary key,
    name varchar(255) not null
);

create table tender
(
    code         varchar(255) primary key,
    currency     varchar(255) check (currency in ('RUB', 'BYN')) not null,
    status_id    bigint not null,
    name         varchar(2000) not null,
    start_date   timestamp not null,
    end_date     timestamp not null,
    publish_date timestamp not null,
    company      varchar(255) not null,
    link         varchar(255),
    start_price  varchar(255),
    foreign key (status_id) references status (id)
);
