version: "3"

services:
  db-postgres:
    env_file:
      - default.env
    image: postgres:16-alpine3.17
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d tender -U username" ]
      interval: 10s
      timeout: 3s
      retries: 5
    ports:
      - "5555:5432"


volumes:
  postgresql-data:
