create table if not exists status
(
    id   bigint generated by default as identity primary key,
    name varchar(255) not null
);

create table if not exists tender
(
    code         varchar(255) primary key,
    currency     varchar(255) check (currency in ('RUB', 'BYN')) not null,
    status_id    bigint not null,
    name         varchar(2000) not null,
    start_date   timestamp,
    end_date     timestamp not null,
    publish_date timestamp not null,
    company      varchar(255) not null,
    link         varchar(255),
    start_price  varchar(255),
    foreign key (status_id) references status (id)
);

create table if not exists xpath (
    id           bigint generated by default as identity primary key,
    code         varchar(255),
    company      varchar(255) not null,
    currency     varchar(255) not null,
    end_date     varchar(255) not null,
    link         varchar(255),
    link_site    varchar(255) not null,
    login_button varchar(255),
    login_link   varchar(255),
    name         varchar(255) not null,
    password     varchar(255),
    publish_date varchar(255) not null,
    start_date   varchar(255),
    start_price  varchar(255),
    next_button  varchar(255),
    status       varchar(255) not null,
    username     varchar(255)
);

create table if not exists active_action (
    id           bigint generated by default as identity primary key,
    xpath_id     bigint,
    xpath_path   varchar(255) not null,
    number       int not null,
    foreign key (xpath_id) references xpath (id)
);

create table if not exists xpath_active_actions (
    xpath_id          bigint not null,
    active_actions_id bigint not null,
    foreign key (xpath_id) references xpath (id),
    foreign key (active_actions_id) references active_action (id)
);



INSERT INTO xpath (id, code, company, currency, end_date, link, link_site, login_button, login_link, name,
                          next_button, password, publish_date, start_date, start_price, status, username)
VALUES (1, '//*[@id="25399118176800742"]/tbody/tr[*]/td[2]', '//*[@id="25399118176800742"]/tbody/tr[*]/td[5]',
        '//*[@id="25399118176800742"]/tbody/tr[*]/td[7]', '//*[@id="25399118176800742"]/tbody/tr[*]/td[10]',
        '//*[@id="25399118176800742"]/tbody/tr[*]/td[3]/a',
        'https://etp.tatneft.ru/pls/tzp/f?p=220:562:5015209375285::::P562_OPEN_MODE,GLB_NAV_ROOT_ID,GLB_NAV_ID:,12920020,12920020',
        'lo2', 'log2', '//*[@id="25399118176800742"]/tbody/tr[*]/td[3]',
        '//*[@id="R25399004548800692_data_panel"]/div[2]/ul/li[3]/button', 'p2',
        '//*[@id="25399118176800742"]/tbody/tr[*]/td[8]', '//*[@id="25399118176800742"]/tbody/tr[*]/td[9]',
        '//*[@id="25399118176800742"]/tbody/tr[*]/td[6]', '//*[@id="25399118176800742"]/tbody/tr[*]/td[4]', 'u2');

INSERT INTO active_action (id, number, xpath_path, xpath_id)
VALUES (1, 1, '//*[@id="P562_BARGAINING_TYPE"]/option[5]', 1);

INSERT INTO xpath_active_actions (xpath_id, active_actions_id)
VALUES (1, 1);